version: '{branch}-{build}'
image: Visual Studio 2019
configuration: Release
platform: x64
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME-$env:APPVEYOR_BUILD_NUMBER"
      }
      else
      {
          Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))-$env:APPVEYOR_BUILD_NUMBER"
      }
environment:
  nodejs_version: '16'
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm ci
build_script:
  - npm run compile
# artifacts:
#   - path: dist/*.exe
