name: Windows Build

on:
  push:
  pull_request:
  release:
    types: [published, prereleased]

env:
  CURVER: '0.0.1'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: yarn
      - run: yarn build

      - uses: actions/upload-artifact@v2-preview
        with:
          name: PTA-Next-Setup.exe
          path: 'dist/electron/Packaged/PTA-Next Setup ${{ env.CURVER }}.exe'

      - uses: actions/upload-artifact@v2-preview
        with:
          name: PTA-Next-Portable.7z
          path: 'dist/electron/Packaged/PTA-Next-${{ env.CURVER }}-win.7z'

      - name: Upload release
        if: github.event.action == 'published' || github.event.action == 'prereleased'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/electron/Packaged/latest.yml
            dist/electron/Packaged/PTA-Next Setup ${{ env.CURVER }}.exe
            dist/electron/Packaged/PTA-Next Setup ${{ env.CURVER }}.exe.blockmap
            dist/electron/Packaged/PTA-Next-${{ env.CURVER }}-win.7z
